version: "2"
run:
  timeout: 5m
  go: ""
  build-tags: []
  allow-parallel-runners: false
  allow-serial-runners: false
  issues-exit-code: 1
  tests: true
output:
  formats: {}
linters:
  enable:
    - gosec
    - nakedret
    - errorlint
    - gochecksumtype
    - err113
    - goheader
    - noctx
    - bodyclose
    - nonamedreturns
    - nestif
    - tagalign
    - unparam
    - intrange
    - forbidigo
    - importas
    - dogsled
    - inamedparam
    - goprintffuncname
    - whitespace
    - arangolint
    - perfsprint
    - nlreturn
    - nilnil
    - errname
    - exhaustruct
    - misspell
    - tagliatelle
    - wrapcheck
    - errcheck
    - contextcheck
    - nolintlint
    - gocritic
    - predeclared
    - usestdlibvars
    - wsl_v5
    - loggercheck
    - prealloc
    - spancheck
    - revive
    - ineffassign
    - mnd
    - mirror
    - wastedassign
    - noinlineerr
    - zerologlint
    - containedctx
    - interfacebloat
    - durationcheck
    - funcorder
    - exptostd
    - musttag
    - ireturn
    - godox
    - unused
    - testpackage
    - staticcheck
    - unconvert
    - gomodguard
    - copyloopvar
    - recvcheck
    - bidichk
    - rowserrcheck
    - testableexamples
    - sqlclosecheck
    - canonicalheader
    - varnamelen
    - gocognit
    - gochecknoglobals
    - gocyclo
    - reassign
    - exhaustive
    - iface
    - gomoddirectives
    - errchkjson
    - asasalint
    - cyclop
    - protogetter
    - nilnesserr
    - gocheckcompilerdirectives
    - dupl
    - dupword
    - decorder
    - ginkgolinter
    - fatcontext
    - usetesting
    - nilerr
    - embeddedstructfieldcheck
    - tparallel
    - paralleltest
    - maintidx
    - goconst
    - asciicheck
    - sloglint
    - godot
    - grouper
    - iotamixing
    - testifylint
    - modernize
    - promlinter
    - nosprintfhostport
    - unqueryvet
    - gosmopolitan
    - godoclint
    - gochecknoinits
    - forcetypeassert
    - thelper
    - depguard
    - govet
    - makezero
    - funlen
formatters:
  enable:
    - golines
issues:
  max-issues-per-linter: 50
  max-same-issues: 10
