// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.countEventsStmt, err = db.PrepareContext(ctx, CountEvents); err != nil {
		return nil, fmt.Errorf("error preparing query CountEvents: %w", err)
	}
	if q.countEventsByTypeStmt, err = db.PrepareContext(ctx, CountEventsByType); err != nil {
		return nil, fmt.Errorf("error preparing query CountEventsByType: %w", err)
	}
	if q.deleteAllEventsStmt, err = db.PrepareContext(ctx, DeleteAllEvents); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteAllEvents: %w", err)
	}
	if q.deleteEventByGithubIDStmt, err = db.PrepareContext(ctx, DeleteEventByGithubID); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteEventByGithubID: %w", err)
	}
	if q.getEventByGithubIDStmt, err = db.PrepareContext(ctx, GetEventByGithubID); err != nil {
		return nil, fmt.Errorf("error preparing query GetEventByGithubID: %w", err)
	}
	if q.getEventTypesStmt, err = db.PrepareContext(ctx, GetEventTypes); err != nil {
		return nil, fmt.Errorf("error preparing query GetEventTypes: %w", err)
	}
	if q.getEventsStmt, err = db.PrepareContext(ctx, GetEvents); err != nil {
		return nil, fmt.Errorf("error preparing query GetEvents: %w", err)
	}
	if q.getEventsByActorStmt, err = db.PrepareContext(ctx, GetEventsByActor); err != nil {
		return nil, fmt.Errorf("error preparing query GetEventsByActor: %w", err)
	}
	if q.getEventsByRepoStmt, err = db.PrepareContext(ctx, GetEventsByRepo); err != nil {
		return nil, fmt.Errorf("error preparing query GetEventsByRepo: %w", err)
	}
	if q.getEventsByTypeStmt, err = db.PrepareContext(ctx, GetEventsByType); err != nil {
		return nil, fmt.Errorf("error preparing query GetEventsByType: %w", err)
	}
	if q.getEventsSinceStmt, err = db.PrepareContext(ctx, GetEventsSince); err != nil {
		return nil, fmt.Errorf("error preparing query GetEventsSince: %w", err)
	}
	if q.getLatestEventStmt, err = db.PrepareContext(ctx, GetLatestEvent); err != nil {
		return nil, fmt.Errorf("error preparing query GetLatestEvent: %w", err)
	}
	if q.upsertEventStmt, err = db.PrepareContext(ctx, UpsertEvent); err != nil {
		return nil, fmt.Errorf("error preparing query UpsertEvent: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.countEventsStmt != nil {
		if cerr := q.countEventsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing countEventsStmt: %w", cerr)
		}
	}
	if q.countEventsByTypeStmt != nil {
		if cerr := q.countEventsByTypeStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing countEventsByTypeStmt: %w", cerr)
		}
	}
	if q.deleteAllEventsStmt != nil {
		if cerr := q.deleteAllEventsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteAllEventsStmt: %w", cerr)
		}
	}
	if q.deleteEventByGithubIDStmt != nil {
		if cerr := q.deleteEventByGithubIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteEventByGithubIDStmt: %w", cerr)
		}
	}
	if q.getEventByGithubIDStmt != nil {
		if cerr := q.getEventByGithubIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getEventByGithubIDStmt: %w", cerr)
		}
	}
	if q.getEventTypesStmt != nil {
		if cerr := q.getEventTypesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getEventTypesStmt: %w", cerr)
		}
	}
	if q.getEventsStmt != nil {
		if cerr := q.getEventsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getEventsStmt: %w", cerr)
		}
	}
	if q.getEventsByActorStmt != nil {
		if cerr := q.getEventsByActorStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getEventsByActorStmt: %w", cerr)
		}
	}
	if q.getEventsByRepoStmt != nil {
		if cerr := q.getEventsByRepoStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getEventsByRepoStmt: %w", cerr)
		}
	}
	if q.getEventsByTypeStmt != nil {
		if cerr := q.getEventsByTypeStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getEventsByTypeStmt: %w", cerr)
		}
	}
	if q.getEventsSinceStmt != nil {
		if cerr := q.getEventsSinceStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getEventsSinceStmt: %w", cerr)
		}
	}
	if q.getLatestEventStmt != nil {
		if cerr := q.getLatestEventStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getLatestEventStmt: %w", cerr)
		}
	}
	if q.upsertEventStmt != nil {
		if cerr := q.upsertEventStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing upsertEventStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                        DBTX
	tx                        *sql.Tx
	countEventsStmt           *sql.Stmt
	countEventsByTypeStmt     *sql.Stmt
	deleteAllEventsStmt       *sql.Stmt
	deleteEventByGithubIDStmt *sql.Stmt
	getEventByGithubIDStmt    *sql.Stmt
	getEventTypesStmt         *sql.Stmt
	getEventsStmt             *sql.Stmt
	getEventsByActorStmt      *sql.Stmt
	getEventsByRepoStmt       *sql.Stmt
	getEventsByTypeStmt       *sql.Stmt
	getEventsSinceStmt        *sql.Stmt
	getLatestEventStmt        *sql.Stmt
	upsertEventStmt           *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                        tx,
		tx:                        tx,
		countEventsStmt:           q.countEventsStmt,
		countEventsByTypeStmt:     q.countEventsByTypeStmt,
		deleteAllEventsStmt:       q.deleteAllEventsStmt,
		deleteEventByGithubIDStmt: q.deleteEventByGithubIDStmt,
		getEventByGithubIDStmt:    q.getEventByGithubIDStmt,
		getEventTypesStmt:         q.getEventTypesStmt,
		getEventsStmt:             q.getEventsStmt,
		getEventsByActorStmt:      q.getEventsByActorStmt,
		getEventsByRepoStmt:       q.getEventsByRepoStmt,
		getEventsByTypeStmt:       q.getEventsByTypeStmt,
		getEventsSinceStmt:        q.getEventsSinceStmt,
		getLatestEventStmt:        q.getLatestEventStmt,
		upsertEventStmt:           q.upsertEventStmt,
	}
}
