// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: events.sql

package db

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"

	types "github.com/larsartmann/go-localsync/pkg/types"
)

const CountEvents = `-- name: CountEvents :one
SELECT COUNT(*) as count FROM events
`

// Count total number of events
//
//	SELECT COUNT(*) as count FROM events
func (q *Queries) CountEvents(ctx context.Context) (int64, error) {
	row := q.queryRow(ctx, q.countEventsStmt, CountEvents)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const CountEventsByType = `-- name: CountEventsByType :one
SELECT COUNT(*) as count FROM events
WHERE type = ?
`

// Count events by type
//
//	SELECT COUNT(*) as count FROM events
//	WHERE type = ?
func (q *Queries) CountEventsByType(ctx context.Context, type_ string) (int64, error) {
	row := q.queryRow(ctx, q.countEventsByTypeStmt, CountEventsByType, type_)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const DeleteAllEvents = `-- name: DeleteAllEvents :exec
DELETE FROM events
`

// Delete all events (use with caution)
//
//	DELETE FROM events
func (q *Queries) DeleteAllEvents(ctx context.Context) error {
	_, err := q.exec(ctx, q.deleteAllEventsStmt, DeleteAllEvents)
	return err
}

const DeleteEventBySourceID = `-- name: DeleteEventBySourceID :exec
DELETE FROM events WHERE source_id = ?
`

// Delete an event by its source ID
//
//	DELETE FROM events WHERE source_id = ?
func (q *Queries) DeleteEventBySourceID(ctx context.Context, sourceID types.SourceItemID) error {
	_, err := q.exec(ctx, q.deleteEventBySourceIDStmt, DeleteEventBySourceID, sourceID)
	return err
}

const GetEventBySourceID = `-- name: GetEventBySourceID :one
SELECT id, source_id, source, type, actor_login, actor_avatar_url, repo_name, repo_url, created_at, updated_at, raw_json, synced_at FROM events
WHERE source_id = ?
`

// Get a single event by its source ID
//
//	SELECT id, source_id, source, type, actor_login, actor_avatar_url, repo_name, repo_url, created_at, updated_at, raw_json, synced_at FROM events
//	WHERE source_id = ?
func (q *Queries) GetEventBySourceID(ctx context.Context, sourceID types.SourceItemID) (*Events, error) {
	row := q.queryRow(ctx, q.getEventBySourceIDStmt, GetEventBySourceID, sourceID)
	var i Events
	err := row.Scan(
		&i.ID,
		&i.SourceID,
		&i.Source,
		&i.Type,
		&i.ActorLogin,
		&i.ActorAvatarUrl,
		&i.RepoName,
		&i.RepoUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RawJson,
		&i.SyncedAt,
	)
	return &i, err
}

const GetEventTypes = `-- name: GetEventTypes :many
SELECT DISTINCT type FROM events
ORDER BY type
`

// Get distinct event types in the database
//
//	SELECT DISTINCT type FROM events
//	ORDER BY type
func (q *Queries) GetEventTypes(ctx context.Context) ([]string, error) {
	rows, err := q.query(ctx, q.getEventTypesStmt, GetEventTypes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var type_ string
		if err := rows.Scan(&type_); err != nil {
			return nil, err
		}
		items = append(items, type_)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetEvents = `-- name: GetEvents :many
SELECT id, source_id, source, type, actor_login, actor_avatar_url, repo_name, repo_url, created_at, updated_at, raw_json, synced_at FROM events
ORDER BY created_at DESC
LIMIT ? OFFSET ?
`

type GetEventsParams struct {
	Limit  int64 `db:"limit" json:"limit"`
	Offset int64 `db:"offset" json:"offset"`
}

// Get all events, ordered by creation date (newest first)
//
//	SELECT id, source_id, source, type, actor_login, actor_avatar_url, repo_name, repo_url, created_at, updated_at, raw_json, synced_at FROM events
//	ORDER BY created_at DESC
//	LIMIT ? OFFSET ?
func (q *Queries) GetEvents(ctx context.Context, arg *GetEventsParams) ([]*Events, error) {
	rows, err := q.query(ctx, q.getEventsStmt, GetEvents, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Events{}
	for rows.Next() {
		var i Events
		if err := rows.Scan(
			&i.ID,
			&i.SourceID,
			&i.Source,
			&i.Type,
			&i.ActorLogin,
			&i.ActorAvatarUrl,
			&i.RepoName,
			&i.RepoUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RawJson,
			&i.SyncedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetEventsByActor = `-- name: GetEventsByActor :many
SELECT id, source_id, source, type, actor_login, actor_avatar_url, repo_name, repo_url, created_at, updated_at, raw_json, synced_at FROM events
WHERE actor_login = ?
ORDER BY created_at DESC
LIMIT ? OFFSET ?
`

type GetEventsByActorParams struct {
	ActorLogin sql.NullString `db:"actor_login" json:"actorLogin"`
	Limit      int64          `db:"limit" json:"limit"`
	Offset     int64          `db:"offset" json:"offset"`
}

// Get events filtered by actor login
//
//	SELECT id, source_id, source, type, actor_login, actor_avatar_url, repo_name, repo_url, created_at, updated_at, raw_json, synced_at FROM events
//	WHERE actor_login = ?
//	ORDER BY created_at DESC
//	LIMIT ? OFFSET ?
func (q *Queries) GetEventsByActor(ctx context.Context, arg *GetEventsByActorParams) ([]*Events, error) {
	rows, err := q.query(ctx, q.getEventsByActorStmt, GetEventsByActor, arg.ActorLogin, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Events{}
	for rows.Next() {
		var i Events
		if err := rows.Scan(
			&i.ID,
			&i.SourceID,
			&i.Source,
			&i.Type,
			&i.ActorLogin,
			&i.ActorAvatarUrl,
			&i.RepoName,
			&i.RepoUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RawJson,
			&i.SyncedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetEventsByRepo = `-- name: GetEventsByRepo :many
SELECT id, source_id, source, type, actor_login, actor_avatar_url, repo_name, repo_url, created_at, updated_at, raw_json, synced_at FROM events
WHERE repo_name = ?
ORDER BY created_at DESC
LIMIT ? OFFSET ?
`

type GetEventsByRepoParams struct {
	RepoName sql.NullString `db:"repo_name" json:"repoName"`
	Limit    int64          `db:"limit" json:"limit"`
	Offset   int64          `db:"offset" json:"offset"`
}

// Get events filtered by repository name
//
//	SELECT id, source_id, source, type, actor_login, actor_avatar_url, repo_name, repo_url, created_at, updated_at, raw_json, synced_at FROM events
//	WHERE repo_name = ?
//	ORDER BY created_at DESC
//	LIMIT ? OFFSET ?
func (q *Queries) GetEventsByRepo(ctx context.Context, arg *GetEventsByRepoParams) ([]*Events, error) {
	rows, err := q.query(ctx, q.getEventsByRepoStmt, GetEventsByRepo, arg.RepoName, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Events{}
	for rows.Next() {
		var i Events
		if err := rows.Scan(
			&i.ID,
			&i.SourceID,
			&i.Source,
			&i.Type,
			&i.ActorLogin,
			&i.ActorAvatarUrl,
			&i.RepoName,
			&i.RepoUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RawJson,
			&i.SyncedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetEventsBySource = `-- name: GetEventsBySource :many
SELECT id, source_id, source, type, actor_login, actor_avatar_url, repo_name, repo_url, created_at, updated_at, raw_json, synced_at FROM events
WHERE source = ?
ORDER BY created_at DESC
LIMIT ? OFFSET ?
`

type GetEventsBySourceParams struct {
	Source string `db:"source" json:"source"`
	Limit  int64  `db:"limit" json:"limit"`
	Offset int64  `db:"offset" json:"offset"`
}

// Get events filtered by source provider
//
//	SELECT id, source_id, source, type, actor_login, actor_avatar_url, repo_name, repo_url, created_at, updated_at, raw_json, synced_at FROM events
//	WHERE source = ?
//	ORDER BY created_at DESC
//	LIMIT ? OFFSET ?
func (q *Queries) GetEventsBySource(ctx context.Context, arg *GetEventsBySourceParams) ([]*Events, error) {
	rows, err := q.query(ctx, q.getEventsBySourceStmt, GetEventsBySource, arg.Source, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Events{}
	for rows.Next() {
		var i Events
		if err := rows.Scan(
			&i.ID,
			&i.SourceID,
			&i.Source,
			&i.Type,
			&i.ActorLogin,
			&i.ActorAvatarUrl,
			&i.RepoName,
			&i.RepoUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RawJson,
			&i.SyncedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetEventsByType = `-- name: GetEventsByType :many
SELECT id, source_id, source, type, actor_login, actor_avatar_url, repo_name, repo_url, created_at, updated_at, raw_json, synced_at FROM events
WHERE type = ?
ORDER BY created_at DESC
LIMIT ? OFFSET ?
`

type GetEventsByTypeParams struct {
	Type   string `db:"type" json:"type"`
	Limit  int64  `db:"limit" json:"limit"`
	Offset int64  `db:"offset" json:"offset"`
}

// Get events filtered by type
//
//	SELECT id, source_id, source, type, actor_login, actor_avatar_url, repo_name, repo_url, created_at, updated_at, raw_json, synced_at FROM events
//	WHERE type = ?
//	ORDER BY created_at DESC
//	LIMIT ? OFFSET ?
func (q *Queries) GetEventsByType(ctx context.Context, arg *GetEventsByTypeParams) ([]*Events, error) {
	rows, err := q.query(ctx, q.getEventsByTypeStmt, GetEventsByType, arg.Type, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Events{}
	for rows.Next() {
		var i Events
		if err := rows.Scan(
			&i.ID,
			&i.SourceID,
			&i.Source,
			&i.Type,
			&i.ActorLogin,
			&i.ActorAvatarUrl,
			&i.RepoName,
			&i.RepoUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RawJson,
			&i.SyncedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetEventsSince = `-- name: GetEventsSince :many
SELECT id, source_id, source, type, actor_login, actor_avatar_url, repo_name, repo_url, created_at, updated_at, raw_json, synced_at FROM events
WHERE created_at > ?
ORDER BY created_at DESC
`

// Get events created after a specific timestamp (for incremental sync)
//
//	SELECT id, source_id, source, type, actor_login, actor_avatar_url, repo_name, repo_url, created_at, updated_at, raw_json, synced_at FROM events
//	WHERE created_at > ?
//	ORDER BY created_at DESC
func (q *Queries) GetEventsSince(ctx context.Context, createdAt time.Time) ([]*Events, error) {
	rows, err := q.query(ctx, q.getEventsSinceStmt, GetEventsSince, createdAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Events{}
	for rows.Next() {
		var i Events
		if err := rows.Scan(
			&i.ID,
			&i.SourceID,
			&i.Source,
			&i.Type,
			&i.ActorLogin,
			&i.ActorAvatarUrl,
			&i.RepoName,
			&i.RepoUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RawJson,
			&i.SyncedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetLatestEvent = `-- name: GetLatestEvent :one
SELECT id, source_id, source, type, actor_login, actor_avatar_url, repo_name, repo_url, created_at, updated_at, raw_json, synced_at FROM events
ORDER BY created_at DESC
LIMIT 1
`

// Get the most recent event by creation timestamp (for incremental sync)
//
//	SELECT id, source_id, source, type, actor_login, actor_avatar_url, repo_name, repo_url, created_at, updated_at, raw_json, synced_at FROM events
//	ORDER BY created_at DESC
//	LIMIT 1
func (q *Queries) GetLatestEvent(ctx context.Context) (*Events, error) {
	row := q.queryRow(ctx, q.getLatestEventStmt, GetLatestEvent)
	var i Events
	err := row.Scan(
		&i.ID,
		&i.SourceID,
		&i.Source,
		&i.Type,
		&i.ActorLogin,
		&i.ActorAvatarUrl,
		&i.RepoName,
		&i.RepoUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RawJson,
		&i.SyncedAt,
	)
	return &i, err
}

const UpsertEvent = `-- name: UpsertEvent :exec
INSERT INTO events (
    id,
    source_id,
    source,
    type,
    actor_login,
    actor_avatar_url,
    repo_name,
    repo_url,
    created_at,
    updated_at,
    raw_json,
    synced_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP)
ON CONFLICT(source_id) DO UPDATE SET
    source = excluded.source,
    type = excluded.type,
    actor_login = excluded.actor_login,
    actor_avatar_url = excluded.actor_avatar_url,
    repo_name = excluded.repo_name,
    repo_url = excluded.repo_url,
    updated_at = excluded.updated_at,
    raw_json = excluded.raw_json
`

type UpsertEventParams struct {
	ID             types.EventID      `db:"id" json:"id"`
	SourceID       types.SourceItemID `db:"source_id" json:"sourceId"`
	Source         string             `db:"source" json:"source"`
	Type           string             `db:"type" json:"type"`
	ActorLogin     sql.NullString     `db:"actor_login" json:"actorLogin"`
	ActorAvatarUrl sql.NullString     `db:"actor_avatar_url" json:"actorAvatarUrl"`
	RepoName       sql.NullString     `db:"repo_name" json:"repoName"`
	RepoUrl        sql.NullString     `db:"repo_url" json:"repoUrl"`
	CreatedAt      time.Time          `db:"created_at" json:"createdAt"`
	UpdatedAt      time.Time          `db:"updated_at" json:"updatedAt"`
	RawJson        json.RawMessage    `db:"raw_json" json:"rawJson"`
}

// Insert an event, updating if it already exists (conflict resolution)
//
//	INSERT INTO events (
//	    id,
//	    source_id,
//	    source,
//	    type,
//	    actor_login,
//	    actor_avatar_url,
//	    repo_name,
//	    repo_url,
//	    created_at,
//	    updated_at,
//	    raw_json,
//	    synced_at
//	) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP)
//	ON CONFLICT(source_id) DO UPDATE SET
//	    source = excluded.source,
//	    type = excluded.type,
//	    actor_login = excluded.actor_login,
//	    actor_avatar_url = excluded.actor_avatar_url,
//	    repo_name = excluded.repo_name,
//	    repo_url = excluded.repo_url,
//	    updated_at = excluded.updated_at,
//	    raw_json = excluded.raw_json
func (q *Queries) UpsertEvent(ctx context.Context, arg *UpsertEventParams) error {
	_, err := q.exec(ctx, q.upsertEventStmt, UpsertEvent,
		arg.ID,
		arg.SourceID,
		arg.Source,
		arg.Type,
		arg.ActorLogin,
		arg.ActorAvatarUrl,
		arg.RepoName,
		arg.RepoUrl,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.RawJson,
	)
	return err
}
