package db

import (
	"database/sql"
	"encoding/json"

	"github.com/larsartmann/go-localsync/pkg/types"
)

// PaginationMixin embeds common pagination parameters (Limit/Offset).
// Used by all Get* query parameter structs that support pagination.
//
// NOTE: This file contains manual mixin types for code reuse.
// These are NOT auto-generated by sqlc and will NOT be overwritten.
// However, the structs in events.sql.go that USE these mixins ARE
// auto-generated and will need manual updates after `sqlc generate`.
type PaginationMixin struct {
	Limit  int64 `db:"limit"  json:"limit"`
	Offset int64 `db:"offset" json:"offset"`
}

// EventCoreMixin embeds fields common to both Events (result) and
// UpsertEventParams. This captures the shared event data structure.
//
// NOTE: This file contains manual mixin types for code reuse.
// These are NOT auto-generated by sqlc and will NOT be overwritten.
type EventCoreMixin struct {
	RawJson        json.RawMessage     `db:"raw_json"         json:"rawJson"`
	GithubID       types.GithubEventID `db:"github_id"        json:"githubId"`
	ActorLogin     sql.NullString      `db:"actor_login"      json:"actorLogin"`
	ActorAvatarUrl sql.NullString      `db:"actor_avatar_url" json:"actorAvatarUrl"`
	RepoName       sql.NullString      `db:"repo_name"        json:"repoName"`
	RepoUrl        sql.NullString      `db:"repo_url"         json:"repoUrl"`
}
