// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
	"time"

	types "github.com/larsartmann/go-localsync/pkg/types"
)

type Querier interface {
	// Count total number of events
	//
	//  SELECT COUNT(*) as count FROM events
	CountEvents(ctx context.Context) (int64, error)
	// Count events by type
	//
	//  SELECT COUNT(*) as count FROM events
	//  WHERE type = ?
	CountEventsByType(ctx context.Context, type_ string) (int64, error)
	// Delete all events (use with caution)
	//
	//  DELETE FROM events
	DeleteAllEvents(ctx context.Context) error
	// Delete an event by its source ID
	//
	//  DELETE FROM events WHERE source_id = ?
	DeleteEventBySourceID(ctx context.Context, sourceID types.SourceItemID) error
	// Get a single event by its source ID
	//
	//  SELECT id, source_id, source, type, actor_login, actor_avatar_url, repo_name, repo_url, created_at, updated_at, raw_json, synced_at FROM events
	//  WHERE source_id = ?
	GetEventBySourceID(ctx context.Context, sourceID types.SourceItemID) (*Events, error)
	// Get distinct event types in the database
	//
	//  SELECT DISTINCT type FROM events
	//  ORDER BY type
	GetEventTypes(ctx context.Context) ([]string, error)
	// Get all events, ordered by creation date (newest first)
	//
	//  SELECT id, source_id, source, type, actor_login, actor_avatar_url, repo_name, repo_url, created_at, updated_at, raw_json, synced_at FROM events
	//  ORDER BY created_at DESC
	//  LIMIT ? OFFSET ?
	GetEvents(ctx context.Context, arg *GetEventsParams) ([]*Events, error)
	// Get events filtered by actor login
	//
	//  SELECT id, source_id, source, type, actor_login, actor_avatar_url, repo_name, repo_url, created_at, updated_at, raw_json, synced_at FROM events
	//  WHERE actor_login = ?
	//  ORDER BY created_at DESC
	//  LIMIT ? OFFSET ?
	GetEventsByActor(ctx context.Context, arg *GetEventsByActorParams) ([]*Events, error)
	// Get events filtered by repository name
	//
	//  SELECT id, source_id, source, type, actor_login, actor_avatar_url, repo_name, repo_url, created_at, updated_at, raw_json, synced_at FROM events
	//  WHERE repo_name = ?
	//  ORDER BY created_at DESC
	//  LIMIT ? OFFSET ?
	GetEventsByRepo(ctx context.Context, arg *GetEventsByRepoParams) ([]*Events, error)
	// Get events filtered by source provider
	//
	//  SELECT id, source_id, source, type, actor_login, actor_avatar_url, repo_name, repo_url, created_at, updated_at, raw_json, synced_at FROM events
	//  WHERE source = ?
	//  ORDER BY created_at DESC
	//  LIMIT ? OFFSET ?
	GetEventsBySource(ctx context.Context, arg *GetEventsBySourceParams) ([]*Events, error)
	// Get events filtered by type
	//
	//  SELECT id, source_id, source, type, actor_login, actor_avatar_url, repo_name, repo_url, created_at, updated_at, raw_json, synced_at FROM events
	//  WHERE type = ?
	//  ORDER BY created_at DESC
	//  LIMIT ? OFFSET ?
	GetEventsByType(ctx context.Context, arg *GetEventsByTypeParams) ([]*Events, error)
	// Get events created after a specific timestamp (for incremental sync)
	//
	//  SELECT id, source_id, source, type, actor_login, actor_avatar_url, repo_name, repo_url, created_at, updated_at, raw_json, synced_at FROM events
	//  WHERE created_at > ?
	//  ORDER BY created_at DESC
	GetEventsSince(ctx context.Context, createdAt time.Time) ([]*Events, error)
	// Get the most recent event by creation timestamp (for incremental sync)
	//
	//  SELECT id, source_id, source, type, actor_login, actor_avatar_url, repo_name, repo_url, created_at, updated_at, raw_json, synced_at FROM events
	//  ORDER BY created_at DESC
	//  LIMIT 1
	GetLatestEvent(ctx context.Context) (*Events, error)
	// Insert an event, updating if it already exists (conflict resolution)
	//
	//  INSERT INTO events (
	//      id,
	//      source_id,
	//      source,
	//      type,
	//      actor_login,
	//      actor_avatar_url,
	//      repo_name,
	//      repo_url,
	//      created_at,
	//      updated_at,
	//      raw_json,
	//      synced_at
	//  ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP)
	//  ON CONFLICT(source_id) DO UPDATE SET
	//      source = excluded.source,
	//      type = excluded.type,
	//      actor_login = excluded.actor_login,
	//      actor_avatar_url = excluded.actor_avatar_url,
	//      repo_name = excluded.repo_name,
	//      repo_url = excluded.repo_url,
	//      updated_at = excluded.updated_at,
	//      raw_json = excluded.raw_json
	UpsertEvent(ctx context.Context, arg *UpsertEventParams) error
}

var _ Querier = (*Queries)(nil)
